name: app2021
description: Paróquia Santa Bárbara.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_form_builder: ^9.1.1
  get: 4.1.4
  get_storage: ^2.0.2

  # flutter_boom_menu: ^1.0.2
  line_icons: ^2.0.1
  flutter_circular_text: "^0.3.1"
  flutter_carousel_slider: ^1.0.8

  google_fonts: ^2.0.0
  cloud_firestore: ^4.12.0
  cloud_firestore_web: ^3.8.2
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  firebase_storage: ^11.4.0
  firebase_analytics: ^10.6.2
  firebase_storage_web: ^3.3.9

  rflutter_alert: ^2.0.2

  # flutter_facebook_auth: ^3.3.2+2
  provider: ^5.0.0
  flutter:
    sdk: flutter
  google_sign_in: ^5.4.2

  cupertino_icons: ^1.0.2
  flip_card: ^0.5.0
  uuid: ^3.0.4
  # flat_dialog: ^1.1.1
  
  path_provider: ^2.0.2
  # flutter_gifimage: ^1.0.1
  image_picker: ^0.8.0+3


  html_unescape: ^2.0.0
  random_color: ^1.0.5
  shape_of_view_null_safe: ^2.0.0
  
  circular_countdown_timer: ^0.2.0
  geolocator: ^7.2.0
  geocoding: ^2.0.0
  slide_popup_dialog_null_safety: ^1.0.0
  google_maps_flutter: ^2.0.6
  flip_drawer: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  platform: ^3.1.0

flutter:
  uses-material-design: true    
  assets:
    - assets/images/
    - assets/icon/
    - assets/videos/
    - assets/data/